# Generated by Django 5.2.7 on 2025-10-23 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('bloqueado', models.BooleanField(default=False, help_text='Marcado si no se encuentra físicamente / extraviado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparada', 'Preparada'), ('cancelada', 'Cancelada'), ('entregada', 'Entregada'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible_al_crear', models.BooleanField(default=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='expediente.legajo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expediente.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('bloqueado_en_prep', models.BooleanField(default=False, help_text='Marcado si el legajo estaba bloqueado/extraviado en preparación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('devuelto_en', models.DateTimeField(blank=True, null=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='expediente.legajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='expediente.solicitud')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('legajo',), name='unico_prestamo_activo_por_legajo')],
            },
        ),
    ]
