# Generated by Django 5.2.7 on 2025-10-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='bloqueado_en_prep',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo para entrega'), ('extraviado', 'Extraviado'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20),
        ),
    ]
