# Generated by Django 5.2.7 on 2025-10-24 14:29

from django.db import migrations


def seed_prestamo_estado(apps, schema_editor):
    Prestamo = apps.get_model('expediente', 'Prestamo')

    for prestamo in Prestamo.objects.all():
        if prestamo.devuelto_en:
            estado = 'devuelto'
            activo = False
        elif prestamo.entregado_en:
            estado = 'entregado'
            activo = True
        else:
            estado = 'pendiente'
            activo = prestamo.activo

        if prestamo.estado != estado or prestamo.activo != activo:
            prestamo.estado = estado
            prestamo.activo = activo
            prestamo.save(update_fields=['estado', 'activo'])


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_remove_prestamo_bloqueado_en_prep_prestamo_estado'),
    ]

    operations = [
        migrations.RunPython(seed_prestamo_estado, reverse_code=migrations.RunPython.noop),
    ]
